### ISSUE TITLE
Cannot build on macOS 10.15.6

### ISSUE THREAD

**Issue by SeptemberHX** [ntop/n2n#385]
```shell
gcc -g -O2 -I/usr/local/opt/openssl@1.1/include -I ./include        -c -o src/edge.o src/edge.c
src/edge.c:855:40: error: implicit declaration of function 'OpenSSL_version' is invalid in C99
      [-Werror,-Wimplicit-function-declaration]
  traceEvent(TRACE_NORMAL, "Using %s", OpenSSL_version(0));
                                       ^
1 error generated.
make: *** [src/edge.o] Error 1
```

After searching with Google, I solved the problem above by adding  `#include <openssl/crypto.h>` in `src/edge.c`.

And another problem appeared:

```shell
/Library/Developer/CommandLineTools/usr/bin/ranlib: file: libn2n.a(transform_aes.o) has no symbols
/Library/Developer/CommandLineTools/usr/bin/ranlib: file: libn2n.a(tuntap_freebsd.o) has no symbols
/Library/Developer/CommandLineTools/usr/bin/ranlib: file: libn2n.a(tuntap_netbsd.o) has no symbols
/Library/Developer/CommandLineTools/usr/bin/ranlib: file: libn2n.a(tuntap_linux.o) has no symbols
/Library/Developer/CommandLineTools/usr/bin/ranlib: file: libn2n.a(edge_utils_win32.o) has no symbols
gcc -g -O2 -I/usr/local/opt/openssl@1.1/include -I ./include      src/edge.c -L/usr/local/opt/openssl@1.1/lib/ libn2n.a  -o edge
Undefined symbols for architecture x86_64:
  "_BIO_ctrl", referenced from:
      _openssl_err_as_string in libn2n.a(transform_cc20.o)
  "_BIO_free", referenced from:
      _openssl_err_as_string in libn2n.a(transform_cc20.o)
  "_BIO_new", referenced from:
      _openssl_err_as_string in libn2n.a(transform_cc20.o)
  "_BIO_s_mem", referenced from:
      _openssl_err_as_string in libn2n.a(transform_cc20.o)
  "_ERR_print_errors", referenced from:
      _openssl_err_as_string in libn2n.a(transform_cc20.o)
  "_EVP_CIPHER_CTX_free", referenced from:
      _transop_deinit_cc20 in libn2n.a(transform_cc20.o)
  "_EVP_CIPHER_CTX_new", referenced from:
      _n2n_transop_cc20_init in libn2n.a(transform_cc20.o)
  "_EVP_CIPHER_CTX_reset", referenced from:
      _transop_encode_cc20 in libn2n.a(transform_cc20.o)
      _transop_decode_cc20 in libn2n.a(transform_cc20.o)
  "_EVP_CIPHER_CTX_set_padding", referenced from:
      _transop_encode_cc20 in libn2n.a(transform_cc20.o)
      _transop_decode_cc20 in libn2n.a(transform_cc20.o)
  "_EVP_DecryptFinal_ex", referenced from:
      _transop_decode_cc20 in libn2n.a(transform_cc20.o)
  "_EVP_DecryptInit_ex", referenced from:
      _transop_decode_cc20 in libn2n.a(transform_cc20.o)
  "_EVP_DecryptUpdate", referenced from:
      _transop_decode_cc20 in libn2n.a(transform_cc20.o)
  "_EVP_EncryptFinal_ex", referenced from:
      _transop_encode_cc20 in libn2n.a(transform_cc20.o)
  "_EVP_EncryptInit_ex", referenced from:
      _transop_encode_cc20 in libn2n.a(transform_cc20.o)
  "_EVP_EncryptUpdate", referenced from:
      _transop_encode_cc20 in libn2n.a(transform_cc20.o)
  "_EVP_chacha20", referenced from:
      _n2n_transop_cc20_init in libn2n.a(transform_cc20.o)
  "_OpenSSL_version", referenced from:
      _main in edge-26e9d0.o
  "_SHA256", referenced from:
      _n2n_transop_cc20_init in libn2n.a(transform_cc20.o)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [edge] Error 1
```

Solved successfully by modifying configure.ac with `N2N_LIBS=-lcrypto`

**Comment by jonahzheng** [comment]
try 2.6-stable
#278

**Comment by jonahzheng** [comment]
@SeptemberHX you can pull one request.

**Comment by SeptemberHX** [comment]
> @SeptemberHX you can pull one request.

I'd like to pull one request, but I don't think it's the best solution to modify configure.ac with `N2N_LIBS=-lcrypto` since I saw `AC_CHECK_LIB([crypto], [AES_cbc_encrypt])` in configure.ac.
I am not familiar with configure.ac, so I decided to post my solution and wait for others to provide a more elegant way to solve it.

**Comment by Logan007** [comment]
Is this still an issue?

**Comment by SeptemberHX** [comment]
> Is this still an issue?

Just test with the dev branch, and it works fine wit Big Sur now. Thanks for your work !
